### ISSUE TITLE
Error report fot Blender v3.3

### ISSUE THREAD

**Issue by SiulroKe** [IngoClemens/blender#3]
![image](https://user-images.githubusercontent.com/101232282/216869683-c8a263b1-2f02-4a8d-b0c9-f5198218a2c4.png)
![image](https://user-images.githubusercontent.com/101232282/216869701-37df374e-27e5-46b9-a370-9bf10573243c.png)
![image](https://user-images.githubusercontent.com/101232282/216869708-ff992a1e-2c1e-474b-8165-531804d63897.png)
你的插件我很喜欢, 但是我在使用的时候, 经常会因为小问题导致出现错误而无法继续使用, 你有空的时候可以看下吗

**Comment by IngoClemens** [comment]
Is this one error or several? As it seems some of these are file system related.
Since these are not common issues I assume it's something local which makes it even harder to identify.
For instance, the second one exits because it cannot find the directory: D:\SoftWart office\blender-3.2.2-windows-x64\3.2\datafiles\studiolights\world\
This should be a regular Blender path and it should exist.
This is nothing which can be checked from remote.

Also, please report any issues in english only. Thank you.

**Comment by SiulroKe** [comment]
The above figure shows several separate errors, all of which are caused by different errors when generating preview images.
Usually I have to copy the file into a new blender file and work again

**Comment by romkas27** [comment]
Hello, Ingo Clemens. Thank you for your addon. It’s amazing. But I have these issues too. It works very well but suddenly give me errors. And only solution is too copy-paste all collections in new file.

**Comment by IngoClemens** [comment]
Since the error doesn’t happen all the time it would be best to provide a sample scene file to reproduce the issue and check for inconsistencies.

**Comment by IngoClemens** [comment]
Closed due to the lack of feedback and not being reproducible.
